version: '3'

services:
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
      target: nginx-stage
      args:
        - VUE_APP_API=$VUE_APP_API
        - VUE_APP_API_KEY=$VUE_APP_API_KEY
    ports: ["8080:80"]

  backend:
    build:
      context: ./
      dockerfile: Dockerfile
      target: node-stage
      args:
        - VUE_APP_API=$VUE_APP_API
        - VUE_APP_API_KEY=$VUE_APP_API_KEY
    ports: ["3000:3000"]
    expose:
      - "3000"
    command: 'node server'
